#!/usr/bin/env ruby
# frozen_string_literal: true

require 'pp'
require './lib/venue'

venue_path = ENV['VENUE_RC'] || '.venue'
dotpaths   = ENV['VENUE_DOTFILES'] || (File.exist?(venue_path) && File.read(venue_path)) || ''
required   = (ENV['VENUE_REQUIRED'] || '').split(/\s*,\s*/)
normalized = dotpaths.split(/[,\n]+/).select { |fn| File.exist? fn }
missing    = required - normalized
raise "Missing required files #{missing.join(', ')}" unless missing.empty?

if normalized.empty?
  r, e, s = run_cmd('dotenv', *ARGV)
else
  r, e, s = run_cmd('dotenv', '-f', normalized.join(','), *ARGV)
end

if e&.empty?
  puts r
else
  $stderr << e
  exit s.to_i
end
